// === Identity ===

export type Priority = 'low' | 'normal' | 'high' | 'urgent';

export type TaskType =
  | 'coding'
  | 'research'
  | 'docs'
  | 'testing'
  | 'review'
  | 'ops'
  | 'analysis';

// === Three-axis status ===
//
// The PRD separates agent claim / validator verdict / human decision (§5,
// UX principle #2). The prototype previously collapsed these into one
// `status` enum; they're now four explicit axes — one for queue lifecycle
// and three for the orthogonal verdicts. UI buckets are derived via
// `taskBucket()` below.

// Where does this task live in your queue right now?
export type LifecycleStatus =
  | 'inbox'      // captured, no agent
  | 'queued'     // assigned, not started
  | 'running'    // active run in progress
  | 'blocked'    // waiting on user input, missing creds, external dep
  | 'done'       // most recent run terminated; verdicts determine bucket
  | 'cancelled'  // user-killed before completion
  | 'archived';

// What did the latest run terminate with (if any)?
export type ClaimedStatus =
  | 'none'       // no run has terminated yet
  | 'succeeded'  // agent claims success
  | 'failed';    // agent reports its own failure

// What did the deterministic validator find on the latest run?
//
// `judged_ok` / `judged_concerns` are the LLM-as-judge band (Phase 9.3) —
// distinct from `verified` so a judge result alone never clears
// `unverified`. Use them for research / docs tasks where deterministic
// checks miss the meaningful failure modes.
export type ValidationStatus =
  | 'not_applicable'
  | 'pending'
  | 'verified'
  | 'partially_verified'
  | 'unverified'
  | 'failed'
  | 'judged_ok'
  | 'judged_concerns';

// What did the human decide?
export type ReviewStatus =
  | 'not_required'
  | 'pending'
  | 'accepted'
  | 'rejected'
  | 'needs_changes';

// === Run ===

export type RunStatus = 'running' | 'succeeded' | 'failed' | 'cancelled' | 'unknown';

export type ActivityType =
  // Phase 7.2 — emitted by the shim per stream-json event
  | 'tool_call_started'
  | 'tool_call_result'
  | 'tool_call_error'
  | 'thinking'
  | 'subagent_spawned'
  | 'permission_requested'
  // run-lifecycle events
  | 'started'
  | 'completed'
  // legacy values still produced by the InMemoryRepository fixture
  | 'read'
  | 'wrote'
  | 'ran'
  | 'thought';

export interface Activity {
  id?: string; // unique within a run; generated by the shim
  timestamp: string;
  type: ActivityType;
  detail: string;
  // Phase 7.2 — links tool_call_started ↔ tool_call_result/error.
  // Equals claude's tool_use.id from the stream-json event.
  toolCallId?: string;
  // For hierarchical collapse (e.g. all activity inside a Task subagent).
  parentEventId?: string;
  toolName?: string;
}

export interface ValidationCheck {
  label: string;
  status: 'pass' | 'fail' | 'warn';
  evidence?: string;
  // Phase 9.2 — written by tools/validator.mjs.
  contractId?: string;
  contractType?: string;
}

// Phase 9.4 — Anthropic's prompt caching breaks single-`tokens` accounting.
// Splitting the fields out keeps cost reconciliation honest without
// pretending we know which tokens belong to which task.
export interface TokenUsage {
  input?: number | null;
  output?: number | null;
  cacheCreate?: number | null;
  cacheRead?: number | null;
}

export interface Artifact {
  name: string;
  type: 'file' | 'diff' | 'log' | 'report';
  preview?: string;
}

export interface Run {
  id: string;
  taskId: string;
  agentId: string;
  status: RunStatus;
  startedAt: string;
  endedAt?: string;
  runtime?: string;
  // `cost` is the legacy single-number USD field (kept for back-compat
  // with views that already render it). Phase 9.4 prefers `costUsd`
  // alongside `tokens` and `costSource` so the UI can mark task-level
  // cost as approximate when caching distorts attribution.
  cost?: number;
  costUsd?: number;
  costSource?: 'estimated' | 'billed';
  // Captured from claude's stream-json `system.init` event. `'none'` means
  // a subscription quota is paying — `costUsd` is then *notional* (what
  // those tokens would cost on the API). `'user' | 'project' | 'org'`
  // mean a real API key, and `costUsd` is actually billed money.
  apiKeySource?: 'none' | 'user' | 'project' | 'org' | string;
  tokens?: TokenUsage;
  agentSummary?: string;
  validationStatus?: ValidationStatus;
  validation?: ValidationCheck[];
  artifacts?: Artifact[];
  activity?: Activity[];
  // Live fields written by tools/claude-shim.mjs as the run progresses
  // (Phase 6.3) and the session id captured for --resume (Phase 6.4).
  sessionId?: string;
  resumedFromSessionId?: string;
  lastToolName?: string;
  toolCount?: number;
  currentActivity?: string;
  updatedAt?: string;
  // Set by the console-server's stale-run sweep (Phase 7.1) when a run
  // is marked 'unknown' because its daemon disappeared without writing
  // a terminal status. Values: 'no_heartbeat' for now; expand later.
  terminationReason?: string;
}

// === Task ===

// Files attached to a user message. The prototype embeds the bytes inline
// as a base-64 data URL — fine for small uploads (screenshots, docs) and
// it survives the JSONL queue → daemon → task.json round-trip without a
// separate blob store. Swap to a content-addressed store under
// `.agent-console/attachments/` if/when payload sizes grow.
export interface Attachment {
  name: string;
  size: number;
  mimeType: string;
  dataUrl: string;
}

export interface Message {
  from: 'agent' | 'user';
  text: string;
  timestamp: string;
  attachments?: Attachment[];
}

// Phase 13 — per-task git worktree. Present when the task's `project`
// resolves through the registry (.agent-console/projects.json); the
// daemon then runs in `path` on `branch`. Accept merges the branch into
// `defaultBranch`; archive removes the directory but keeps the branch.
export interface WorktreeInfo {
  path: string;
  branch: string;
  repoPath: string;
  defaultBranch?: string;
  // 'local' merges on accept; 'github-pr' pushes + opens a PR on accept.
  mergeMode?: 'local' | 'github-pr';
  // Phase 13.1 — one-time worktree setup (e.g. npm install).
  setupStatus?: 'running' | 'done' | 'failed';
  mergedAt?: string;
  mergeCommit?: string;
  // Set when an accept was blocked by a merge conflict.
  mergeConflicts?: string[];
  // Phase 13.2 — github-pr mode: the PR opened on accept, and its state as
  // last polled from GitHub (`gh pr view`).
  prUrl?: string;
  prNumber?: number;
  prState?: 'open' | 'merged' | 'closed';
  prMergedAt?: string;
  prMergeCommit?: string;
  removedAt?: string;
}

// Phase 13 — a registered project from .agent-console/projects.json.
// Tasks whose `project` matches a registered name run in a per-task
// worktree off `defaultBranch`.
export interface ProjectInfo {
  name: string;
  repoPath: string;
  defaultBranch?: string;
  // Shell command run once in each fresh worktree (e.g. `npm install`).
  setupCommand?: string;
  // How accept ships the work: local merge (default) or open a GitHub PR.
  mergeMode?: 'local' | 'github-pr';
}

// Shape of GET /api/tasks/:id/diff — committed work on the task branch
// plus any uncommitted paths still sitting in the worktree.
export interface TaskDiff {
  branch: string;
  defaultBranch: string;
  baseCommit: string;
  stat: string;
  files: { path: string; added: number; deleted: number }[];
  uncommitted: string[];
}

export interface Task {
  id: string;
  title: string;
  description?: string;
  type: TaskType;
  priority: Priority;
  project?: string;
  agentId?: string;
  parentTaskId?: string;

  lifecycleStatus: LifecycleStatus;
  claimedStatus: ClaimedStatus;
  validationStatus: ValidationStatus;
  reviewStatus: ReviewStatus;

  createdAt: string;
  updatedAt: string;

  runs?: Run[];

  messages?: Message[];
  waitingOnUser?: boolean;
  pendingReply?: {
    text: string;
    queuedAt: string;
    attachments?: Attachment[];
  };
  // User has dismissed this task to "Recent"; it stays out of the main
  // tray until they re-engage (sending a message clears this).
  archivedAt?: string;
  // Phase 12.1 — provenance. Free-form: 'ui' | 'hermes' | 'cli' | etc.
  // Server defaults to 'ui' when capture omits it. The UI renders a chip
  // when this is set and not 'ui'.
  createdBy?: string;
  // Phase 13 — set by the server when the daemon runs in a git worktree.
  worktree?: WorktreeInfo;
}

// === Agent ===

export type AgentStatus = 'available' | 'busy' | 'offline';

export interface Agent {
  id: string;
  name: string;
  model: string;
  role: string;
  status: AgentStatus;
  activeTasks: number;
}

// === Derived helpers ===

// UI bucket — derived from the four axes. Replaces the old single `status`
// field for grouping and styling. Keep in sync if axes change.
export type TaskBucket =
  | 'inbox'
  | 'queued'
  | 'running'
  | 'blocked'
  | 'review'
  | 'failed'
  | 'done';

export function taskBucket(task: Task): TaskBucket {
  switch (task.lifecycleStatus) {
    case 'inbox':
      return 'inbox';
    case 'queued':
      return 'queued';
    case 'running':
      return 'running';
    case 'blocked':
      return 'blocked';
    default:
      // lifecycle is done / cancelled / archived: classify by verdicts
      if (task.claimedStatus === 'failed') return 'failed';
      if (task.validationStatus === 'failed') return 'failed';
      if (task.claimedStatus === 'succeeded' && task.reviewStatus === 'pending')
        return 'review';
      return 'done';
  }
}

export function latestRun(task: Task): Run | undefined {
  return task.runs && task.runs.length > 0
    ? task.runs[task.runs.length - 1]
    : undefined;
}

export function totalCost(task: Task): number {
  return (task.runs || []).reduce(
    (sum, r) => sum + (r.costUsd ?? r.cost ?? 0),
    0
  );
}

// Split spend across many tasks into the two billing buckets so the UI
// can render "subscription notional" separately from "actually billed."
export interface SpendSplit {
  subscriptionUsd: number;  // would-have-cost on API; covered by Claude Code plan
  apiUsd: number;           // billed to an API key
  unknownUsd: number;       // run hasn't reported apiKeySource yet
}

export function spendSplit(tasks: Task[]): SpendSplit {
  const out: SpendSplit = { subscriptionUsd: 0, apiUsd: 0, unknownUsd: 0 };
  for (const t of tasks) {
    for (const r of t.runs || []) {
      const usd = r.costUsd ?? r.cost ?? 0;
      if (!usd) continue;
      const mode = billingModeForRun(r);
      if (mode === 'subscription') out.subscriptionUsd += usd;
      else if (mode === 'api') out.apiUsd += usd;
      else out.unknownUsd += usd;
    }
  }
  return out;
}

// Phase 9.5 — task-level cost is a sum-of-runs *estimate*; cache effects
// mean per-task attribution is structurally approximate. Per-run cost
// remains precise. Surface both so the UI can pick the right rendering
// (e.g. `~$0.42` for tasks, `$0.18` for individual runs).
//
// `billingMode` separates "what would this cost on the API" (always
// surfaced as `totalUsd`) from "is the user actually being charged this."
// Subscription runs still emit a USD figure from claude — we mark them
// notional so the UI doesn't pretend it's money out the door.
export type BillingMode = 'subscription' | 'api' | 'mixed' | 'unknown';

export interface TaskCost {
  totalUsd: number;
  isApproximate: boolean;
  runCount: number;
  hasCachedTokens: boolean;
  billingMode: BillingMode;
}

export function billingModeForRun(run: Run): BillingMode {
  if (run.apiKeySource === 'none') return 'subscription';
  if (
    run.apiKeySource === 'user' ||
    run.apiKeySource === 'project' ||
    run.apiKeySource === 'org'
  ) {
    return 'api';
  }
  return 'unknown';
}

export function taskCost(task: Task): TaskCost {
  const runs = task.runs || [];
  const totalUsd = runs.reduce((sum, r) => sum + (r.costUsd ?? r.cost ?? 0), 0);
  const hasCachedTokens = runs.some(
    (r) =>
      (r.tokens?.cacheCreate ?? 0) > 0 || (r.tokens?.cacheRead ?? 0) > 0
  );
  const modes = new Set(runs.map(billingModeForRun));
  modes.delete('unknown');
  let billingMode: BillingMode;
  if (modes.size === 0) billingMode = 'unknown';
  else if (modes.size > 1) billingMode = 'mixed';
  else billingMode = [...modes][0];
  return {
    totalUsd,
    runCount: runs.length,
    hasCachedTokens,
    billingMode,
    // > 1 run OR cached tokens distort attribution → render as `~$X`.
    isApproximate: runs.length > 1 || hasCachedTokens,
  };
}
